[base]
production=false
domain_name=""
ip_address=""
port=0

# Postgres config
[postgres]
host="localhost"
user="postgres"
password="postgres"
port=5431
db="journly"

# Email config
[mailgun_smtp]
login=""
password=""
server=""

[jwt_config]
# secret used to generate/validate access token
access_secret= "secret-token"
# secret used to generate/validate refresh token
refresh_secret= "secret-token"
# Supported algorithms:
#   HS256,
#   HS384,
#   HS512,
#   ES256,
#   ES384,
#   RS256,
#   RS384,
#   RS512,
#   PS256,
#   PS384,
#   PS512,
#   EdDSA,
algorithm="HS256"
