[base]
production=false
domain_name=""
frontend_origin=""
ip_address=""
port=0
allowed_origins=[""]
workers=1

# Postgres config
[postgres]
host="localhost"
user="postgres"
password="postgres"
port=5431
db="postgres"

# Email config
[mailgun_smtp]
login=""
password=""
server=""

[google_oauth]
client_id=""
client_secret=""
redirect_url=""

[jwt_config]
# secret used to generate/validate access token
access_secret= "secret-token"
# secret used to generate/validate refresh token
refresh_secret= "secret-token"
# Supported algorithms:
#   HS256,
#   HS384,
#   HS512,
#   ES256,
#   ES384,
#   RS256,
#   RS384,
#   RS512,
#   PS256,
#   PS384,
#   PS512,
#   EdDSA,
algorithm="HS256"
# expiration time in minutes
access_token_expiration=5
refresh_token_expiration=10080
