# Server address
server_addr="127.0.0.1"

# Server port
server_port=8080

# Postgres config
[db_config]
pg_host="localhost"
pg_user="postgres"
pg_password="postgres"
pg_port=5431
pg_db="journly"


# Redis config
[redis_config]
redis_host="localhost"
redis_port=6379
