[base]
production=false
domain_name=""
frontend_origin=""
ip_address=""
port=0
allowed_origins=[""]
workers=1

[postgres]
host="localhost"
user="postgres"
password="postgres"
port=5431
db="postgres"

[jwt_config]
access_secret= "secret-token"
refresh_secret= "secret-token"
algorithm="HS256"
access_token_expiration=5
refresh_token_expiration=10080


