/* tslint:disable */
/* eslint-disable */
/**
 * journly-server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EncodableTripOverview
 */
export interface EncodableTripOverview {
    /**
     * 
     * @type {string}
     * @memberof EncodableTripOverview
     */
    bannerImage?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof EncodableTripOverview
     */
    endDate?: Date | null;
    /**
     * 
     * @type {string}
     * @memberof EncodableTripOverview
     */
    id: string;
    /**
     * 
     * @type {number}
     * @memberof EncodableTripOverview
     */
    noCollaborators: number;
    /**
     * 
     * @type {Date}
     * @memberof EncodableTripOverview
     */
    startDate?: Date | null;
    /**
     * 
     * @type {string}
     * @memberof EncodableTripOverview
     */
    title?: string | null;
}

/**
 * Check if a given object implements the EncodableTripOverview interface.
 */
export function instanceOfEncodableTripOverview(value: object): value is EncodableTripOverview {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('noCollaborators' in value) || value['noCollaborators'] === undefined) return false;
    return true;
}

export function EncodableTripOverviewFromJSON(json: any): EncodableTripOverview {
    return EncodableTripOverviewFromJSONTyped(json, false);
}

export function EncodableTripOverviewFromJSONTyped(json: any, ignoreDiscriminator: boolean): EncodableTripOverview {
    if (json == null) {
        return json;
    }
    return {
        
        'bannerImage': json['banner_image'] == null ? undefined : json['banner_image'],
        'endDate': json['end_date'] == null ? undefined : (new Date(json['end_date'])),
        'id': json['id'],
        'noCollaborators': json['no_collaborators'],
        'startDate': json['start_date'] == null ? undefined : (new Date(json['start_date'])),
        'title': json['title'] == null ? undefined : json['title'],
    };
}

export function EncodableTripOverviewToJSON(json: any): EncodableTripOverview {
    return EncodableTripOverviewToJSONTyped(json, false);
}

export function EncodableTripOverviewToJSONTyped(value?: EncodableTripOverview | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'banner_image': value['bannerImage'],
        'end_date': value['endDate'] == null ? undefined : ((value['endDate'] as any).toISOString().substring(0,10)),
        'id': value['id'],
        'no_collaborators': value['noCollaborators'],
        'start_date': value['startDate'] == null ? undefined : ((value['startDate'] as any).toISOString().substring(0,10)),
        'title': value['title'],
    };
}

