/* tslint:disable */
/* eslint-disable */
/**
 * journly-server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EncodableCollaborator
 */
export interface EncodableCollaborator {
    /**
     * 
     * @type {string}
     * @memberof EncodableCollaborator
     */
    avatar?: string | null;
    /**
     * 
     * @type {string}
     * @memberof EncodableCollaborator
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof EncodableCollaborator
     */
    permission?: string | null;
    /**
     * 
     * @type {string}
     * @memberof EncodableCollaborator
     */
    username: string;
}

/**
 * Check if a given object implements the EncodableCollaborator interface.
 */
export function instanceOfEncodableCollaborator(value: object): value is EncodableCollaborator {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('username' in value) || value['username'] === undefined) return false;
    return true;
}

export function EncodableCollaboratorFromJSON(json: any): EncodableCollaborator {
    return EncodableCollaboratorFromJSONTyped(json, false);
}

export function EncodableCollaboratorFromJSONTyped(json: any, ignoreDiscriminator: boolean): EncodableCollaborator {
    if (json == null) {
        return json;
    }
    return {
        
        'avatar': json['avatar'] == null ? undefined : json['avatar'],
        'id': json['id'],
        'permission': json['permission'] == null ? undefined : json['permission'],
        'username': json['username'],
    };
}

export function EncodableCollaboratorToJSON(json: any): EncodableCollaborator {
    return EncodableCollaboratorToJSONTyped(json, false);
}

export function EncodableCollaboratorToJSONTyped(value?: EncodableCollaborator | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'avatar': value['avatar'],
        'id': value['id'],
        'permission': value['permission'],
        'username': value['username'],
    };
}

