/* tslint:disable */
/* eslint-disable */
/**
 * journly-server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EncodableUserPreview
 */
export interface EncodableUserPreview {
    /**
     * 
     * @type {string}
     * @memberof EncodableUserPreview
     */
    avatar?: string | null;
    /**
     * 
     * @type {string}
     * @memberof EncodableUserPreview
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof EncodableUserPreview
     */
    username: string;
}

/**
 * Check if a given object implements the EncodableUserPreview interface.
 */
export function instanceOfEncodableUserPreview(value: object): value is EncodableUserPreview {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('username' in value) || value['username'] === undefined) return false;
    return true;
}

export function EncodableUserPreviewFromJSON(json: any): EncodableUserPreview {
    return EncodableUserPreviewFromJSONTyped(json, false);
}

export function EncodableUserPreviewFromJSONTyped(json: any, ignoreDiscriminator: boolean): EncodableUserPreview {
    if (json == null) {
        return json;
    }
    return {
        
        'avatar': json['avatar'] == null ? undefined : json['avatar'],
        'id': json['id'],
        'username': json['username'],
    };
}

export function EncodableUserPreviewToJSON(json: any): EncodableUserPreview {
    return EncodableUserPreviewToJSONTyped(json, false);
}

export function EncodableUserPreviewToJSONTyped(value?: EncodableUserPreview | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'avatar': value['avatar'],
        'id': value['id'],
        'username': value['username'],
    };
}

