/* tslint:disable */
/* eslint-disable */
/**
 * journly-server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { EncodableUserPreview } from './EncodableUserPreview';
import {
    EncodableUserPreviewFromJSON,
    EncodableUserPreviewFromJSONTyped,
    EncodableUserPreviewToJSON,
    EncodableUserPreviewToJSONTyped,
} from './EncodableUserPreview';

/**
 * 
 * @export
 * @interface EncodableExpense
 */
export interface EncodableExpense {
    /**
     * 
     * @type {string}
     * @memberof EncodableExpense
     */
    cost: string;
    /**
     * 
     * @type {string}
     * @memberof EncodableExpense
     */
    currency?: string | null;
    /**
     * 
     * @type {string}
     * @memberof EncodableExpense
     */
    id: string;
    /**
     * 
     * @type {Array<EncodableUserPreview>}
     * @memberof EncodableExpense
     */
    payers: Array<EncodableUserPreview>;
    /**
     * 
     * @type {string}
     * @memberof EncodableExpense
     */
    title?: string | null;
}

/**
 * Check if a given object implements the EncodableExpense interface.
 */
export function instanceOfEncodableExpense(value: object): value is EncodableExpense {
    if (!('cost' in value) || value['cost'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('payers' in value) || value['payers'] === undefined) return false;
    return true;
}

export function EncodableExpenseFromJSON(json: any): EncodableExpense {
    return EncodableExpenseFromJSONTyped(json, false);
}

export function EncodableExpenseFromJSONTyped(json: any, ignoreDiscriminator: boolean): EncodableExpense {
    if (json == null) {
        return json;
    }
    return {
        
        'cost': json['cost'],
        'currency': json['currency'] == null ? undefined : json['currency'],
        'id': json['id'],
        'payers': ((json['payers'] as Array<any>).map(EncodableUserPreviewFromJSON)),
        'title': json['title'] == null ? undefined : json['title'],
    };
}

export function EncodableExpenseToJSON(json: any): EncodableExpense {
    return EncodableExpenseToJSONTyped(json, false);
}

export function EncodableExpenseToJSONTyped(value?: EncodableExpense | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'cost': value['cost'],
        'currency': value['currency'],
        'id': value['id'],
        'payers': ((value['payers'] as Array<any>).map(EncodableUserPreviewToJSON)),
        'title': value['title'],
    };
}

