/* tslint:disable */
/* eslint-disable */
/**
 * journly-server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EncodableDocument
 */
export interface EncodableDocument {
    /**
     * 
     * @type {string}
     * @memberof EncodableDocument
     */
    filename: string;
    /**
     * 
     * @type {string}
     * @memberof EncodableDocument
     */
    id: string;
    /**
     * 
     * @type {number}
     * @memberof EncodableDocument
     */
    sizeBytes: number;
}

/**
 * Check if a given object implements the EncodableDocument interface.
 */
export function instanceOfEncodableDocument(value: object): value is EncodableDocument {
    if (!('filename' in value) || value['filename'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('sizeBytes' in value) || value['sizeBytes'] === undefined) return false;
    return true;
}

export function EncodableDocumentFromJSON(json: any): EncodableDocument {
    return EncodableDocumentFromJSONTyped(json, false);
}

export function EncodableDocumentFromJSONTyped(json: any, ignoreDiscriminator: boolean): EncodableDocument {
    if (json == null) {
        return json;
    }
    return {
        
        'filename': json['filename'],
        'id': json['id'],
        'sizeBytes': json['size_bytes'],
    };
}

export function EncodableDocumentToJSON(json: any): EncodableDocument {
    return EncodableDocumentToJSONTyped(json, false);
}

export function EncodableDocumentToJSONTyped(value?: EncodableDocument | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'filename': value['filename'],
        'id': value['id'],
        'size_bytes': value['sizeBytes'],
    };
}

