/* tslint:disable */
/* eslint-disable */
/**
 * journly-server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EncodablePersonalBudget
 */
export interface EncodablePersonalBudget {
    /**
     * 
     * @type {string}
     * @memberof EncodablePersonalBudget
     */
    accommodationBudget: string;
    /**
     * 
     * @type {string}
     * @memberof EncodablePersonalBudget
     */
    activitiesBudget: string;
    /**
     * 
     * @type {string}
     * @memberof EncodablePersonalBudget
     */
    currency?: string | null;
    /**
     * 
     * @type {string}
     * @memberof EncodablePersonalBudget
     */
    foodDiningBudget: string;
    /**
     * 
     * @type {string}
     * @memberof EncodablePersonalBudget
     */
    shoppingBudget: string;
    /**
     * 
     * @type {string}
     * @memberof EncodablePersonalBudget
     */
    totalBudget: string;
    /**
     * 
     * @type {string}
     * @memberof EncodablePersonalBudget
     */
    transportationBudget: string;
}

/**
 * Check if a given object implements the EncodablePersonalBudget interface.
 */
export function instanceOfEncodablePersonalBudget(value: object): value is EncodablePersonalBudget {
    if (!('accommodationBudget' in value) || value['accommodationBudget'] === undefined) return false;
    if (!('activitiesBudget' in value) || value['activitiesBudget'] === undefined) return false;
    if (!('foodDiningBudget' in value) || value['foodDiningBudget'] === undefined) return false;
    if (!('shoppingBudget' in value) || value['shoppingBudget'] === undefined) return false;
    if (!('totalBudget' in value) || value['totalBudget'] === undefined) return false;
    if (!('transportationBudget' in value) || value['transportationBudget'] === undefined) return false;
    return true;
}

export function EncodablePersonalBudgetFromJSON(json: any): EncodablePersonalBudget {
    return EncodablePersonalBudgetFromJSONTyped(json, false);
}

export function EncodablePersonalBudgetFromJSONTyped(json: any, ignoreDiscriminator: boolean): EncodablePersonalBudget {
    if (json == null) {
        return json;
    }
    return {
        
        'accommodationBudget': json['accommodation_budget'],
        'activitiesBudget': json['activities_budget'],
        'currency': json['currency'] == null ? undefined : json['currency'],
        'foodDiningBudget': json['food_dining_budget'],
        'shoppingBudget': json['shopping_budget'],
        'totalBudget': json['total_budget'],
        'transportationBudget': json['transportation_budget'],
    };
}

export function EncodablePersonalBudgetToJSON(json: any): EncodablePersonalBudget {
    return EncodablePersonalBudgetToJSONTyped(json, false);
}

export function EncodablePersonalBudgetToJSONTyped(value?: EncodablePersonalBudget | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'accommodation_budget': value['accommodationBudget'],
        'activities_budget': value['activitiesBudget'],
        'currency': value['currency'],
        'food_dining_budget': value['foodDiningBudget'],
        'shopping_budget': value['shoppingBudget'],
        'total_budget': value['totalBudget'],
        'transportation_budget': value['transportationBudget'],
    };
}

