/* tslint:disable */
/* eslint-disable */
/**
 * journly-server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EncodableItineraryItem
 */
export interface EncodableItineraryItem {
    /**
     * 
     * @type {string}
     * @memberof EncodableItineraryItem
     */
    activityType?: string | null;
    /**
     * 
     * @type {string}
     * @memberof EncodableItineraryItem
     */
    cost: string;
    /**
     * 
     * @type {Date}
     * @memberof EncodableItineraryItem
     */
    endTime?: Date | null;
    /**
     * 
     * @type {string}
     * @memberof EncodableItineraryItem
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof EncodableItineraryItem
     */
    location?: string | null;
    /**
     * 
     * @type {string}
     * @memberof EncodableItineraryItem
     */
    notes?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof EncodableItineraryItem
     */
    startTime?: Date | null;
    /**
     * 
     * @type {string}
     * @memberof EncodableItineraryItem
     */
    title: string;
}

/**
 * Check if a given object implements the EncodableItineraryItem interface.
 */
export function instanceOfEncodableItineraryItem(value: object): value is EncodableItineraryItem {
    if (!('cost' in value) || value['cost'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    return true;
}

export function EncodableItineraryItemFromJSON(json: any): EncodableItineraryItem {
    return EncodableItineraryItemFromJSONTyped(json, false);
}

export function EncodableItineraryItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): EncodableItineraryItem {
    if (json == null) {
        return json;
    }
    return {
        
        'activityType': json['activity_type'] == null ? undefined : json['activity_type'],
        'cost': json['cost'],
        'endTime': json['end_time'] == null ? undefined : (new Date(json['end_time'])),
        'id': json['id'],
        'location': json['location'] == null ? undefined : json['location'],
        'notes': json['notes'] == null ? undefined : json['notes'],
        'startTime': json['start_time'] == null ? undefined : (new Date(json['start_time'])),
        'title': json['title'],
    };
}

export function EncodableItineraryItemToJSON(json: any): EncodableItineraryItem {
    return EncodableItineraryItemToJSONTyped(json, false);
}

export function EncodableItineraryItemToJSONTyped(value?: EncodableItineraryItem | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'activity_type': value['activityType'],
        'cost': value['cost'],
        'end_time': value['endTime'] == null ? undefined : ((value['endTime'] as any).toISOString()),
        'id': value['id'],
        'location': value['location'],
        'notes': value['notes'],
        'start_time': value['startTime'] == null ? undefined : ((value['startTime'] as any).toISOString()),
        'title': value['title'],
    };
}

