/* tslint:disable */
/* eslint-disable */
/**
 * journly-server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EncodableUser
 */
export interface EncodableUser {
    /**
     * 
     * @type {string}
     * @memberof EncodableUser
     */
    avatar?: string | null;
    /**
     * 
     * @type {string}
     * @memberof EncodableUser
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof EncodableUser
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof EncodableUser
     */
    username: string;
}

/**
 * Check if a given object implements the EncodableUser interface.
 */
export function instanceOfEncodableUser(value: object): value is EncodableUser {
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('username' in value) || value['username'] === undefined) return false;
    return true;
}

export function EncodableUserFromJSON(json: any): EncodableUser {
    return EncodableUserFromJSONTyped(json, false);
}

export function EncodableUserFromJSONTyped(json: any, ignoreDiscriminator: boolean): EncodableUser {
    if (json == null) {
        return json;
    }
    return {
        
        'avatar': json['avatar'] == null ? undefined : json['avatar'],
        'email': json['email'],
        'id': json['id'],
        'username': json['username'],
    };
}

export function EncodableUserToJSON(json: any): EncodableUser {
    return EncodableUserToJSONTyped(json, false);
}

export function EncodableUserToJSONTyped(value?: EncodableUser | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'avatar': value['avatar'],
        'email': value['email'],
        'id': value['id'],
        'username': value['username'],
    };
}

