/* tslint:disable */
/* eslint-disable */
/**
 * journly-server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { EncodableGroupBudget } from './EncodableGroupBudget';
import {
    EncodableGroupBudgetFromJSON,
    EncodableGroupBudgetFromJSONTyped,
    EncodableGroupBudgetToJSON,
    EncodableGroupBudgetToJSONTyped,
} from './EncodableGroupBudget';
import type { EncodableExpense } from './EncodableExpense';
import {
    EncodableExpenseFromJSON,
    EncodableExpenseFromJSONTyped,
    EncodableExpenseToJSON,
    EncodableExpenseToJSONTyped,
} from './EncodableExpense';
import type { EncodablePersonalBudget } from './EncodablePersonalBudget';
import {
    EncodablePersonalBudgetFromJSON,
    EncodablePersonalBudgetFromJSONTyped,
    EncodablePersonalBudgetToJSON,
    EncodablePersonalBudgetToJSONTyped,
} from './EncodablePersonalBudget';

/**
 * 
 * @export
 * @interface EncodableBudgetPlan
 */
export interface EncodableBudgetPlan {
    /**
     * 
     * @type {Array<EncodableExpense>}
     * @memberof EncodableBudgetPlan
     */
    expenses: Array<EncodableExpense>;
    /**
     * 
     * @type {EncodableGroupBudget}
     * @memberof EncodableBudgetPlan
     */
    groupBudget: EncodableGroupBudget;
    /**
     * 
     * @type {EncodablePersonalBudget}
     * @memberof EncodableBudgetPlan
     */
    personalBudget: EncodablePersonalBudget;
    /**
     * 
     * @type {boolean}
     * @memberof EncodableBudgetPlan
     */
    usePersonalBudget: boolean;
}

/**
 * Check if a given object implements the EncodableBudgetPlan interface.
 */
export function instanceOfEncodableBudgetPlan(value: object): value is EncodableBudgetPlan {
    if (!('expenses' in value) || value['expenses'] === undefined) return false;
    if (!('groupBudget' in value) || value['groupBudget'] === undefined) return false;
    if (!('personalBudget' in value) || value['personalBudget'] === undefined) return false;
    if (!('usePersonalBudget' in value) || value['usePersonalBudget'] === undefined) return false;
    return true;
}

export function EncodableBudgetPlanFromJSON(json: any): EncodableBudgetPlan {
    return EncodableBudgetPlanFromJSONTyped(json, false);
}

export function EncodableBudgetPlanFromJSONTyped(json: any, ignoreDiscriminator: boolean): EncodableBudgetPlan {
    if (json == null) {
        return json;
    }
    return {
        
        'expenses': ((json['expenses'] as Array<any>).map(EncodableExpenseFromJSON)),
        'groupBudget': EncodableGroupBudgetFromJSON(json['group_budget']),
        'personalBudget': EncodablePersonalBudgetFromJSON(json['personal_budget']),
        'usePersonalBudget': json['use_personal_budget'],
    };
}

export function EncodableBudgetPlanToJSON(json: any): EncodableBudgetPlan {
    return EncodableBudgetPlanToJSONTyped(json, false);
}

export function EncodableBudgetPlanToJSONTyped(value?: EncodableBudgetPlan | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'expenses': ((value['expenses'] as Array<any>).map(EncodableExpenseToJSON)),
        'group_budget': EncodableGroupBudgetToJSON(value['groupBudget']),
        'personal_budget': EncodablePersonalBudgetToJSON(value['personalBudget']),
        'use_personal_budget': value['usePersonalBudget'],
    };
}

