/* tslint:disable */
/* eslint-disable */
/**
 * journly-server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { EncodableTripOverview } from './EncodableTripOverview';
import {
    EncodableTripOverviewFromJSON,
    EncodableTripOverviewFromJSONTyped,
    EncodableTripOverviewToJSON,
    EncodableTripOverviewToJSONTyped,
} from './EncodableTripOverview';

/**
 * 
 * @export
 * @interface GetTripsResponse
 */
export interface GetTripsResponse {
    /**
     * 
     * @type {Array<EncodableTripOverview>}
     * @memberof GetTripsResponse
     */
    trips: Array<EncodableTripOverview>;
}

/**
 * Check if a given object implements the GetTripsResponse interface.
 */
export function instanceOfGetTripsResponse(value: object): value is GetTripsResponse {
    if (!('trips' in value) || value['trips'] === undefined) return false;
    return true;
}

export function GetTripsResponseFromJSON(json: any): GetTripsResponse {
    return GetTripsResponseFromJSONTyped(json, false);
}

export function GetTripsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetTripsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'trips': ((json['trips'] as Array<any>).map(EncodableTripOverviewFromJSON)),
    };
}

export function GetTripsResponseToJSON(json: any): GetTripsResponse {
    return GetTripsResponseToJSONTyped(json, false);
}

export function GetTripsResponseToJSONTyped(value?: GetTripsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'trips': ((value['trips'] as Array<any>).map(EncodableTripOverviewToJSON)),
    };
}

