/* tslint:disable */
/* eslint-disable */
/**
 * journly-server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { EncodableTripData } from './EncodableTripData';
import {
    EncodableTripDataFromJSON,
    EncodableTripDataFromJSONTyped,
    EncodableTripDataToJSON,
    EncodableTripDataToJSONTyped,
} from './EncodableTripData';

/**
 * 
 * @export
 * @interface GetTripResponse
 */
export interface GetTripResponse {
    /**
     * 
     * @type {EncodableTripData}
     * @memberof GetTripResponse
     */
    trip: EncodableTripData;
}

/**
 * Check if a given object implements the GetTripResponse interface.
 */
export function instanceOfGetTripResponse(value: object): value is GetTripResponse {
    if (!('trip' in value) || value['trip'] === undefined) return false;
    return true;
}

export function GetTripResponseFromJSON(json: any): GetTripResponse {
    return GetTripResponseFromJSONTyped(json, false);
}

export function GetTripResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetTripResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'trip': EncodableTripDataFromJSON(json['trip']),
    };
}

export function GetTripResponseToJSON(json: any): GetTripResponse {
    return GetTripResponseToJSONTyped(json, false);
}

export function GetTripResponseToJSONTyped(value?: GetTripResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'trip': EncodableTripDataToJSON(value['trip']),
    };
}

