/* tslint:disable */
/* eslint-disable */
/**
 * journly-server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { EncodableUser } from './EncodableUser';
import {
    EncodableUserFromJSON,
    EncodableUserFromJSONTyped,
    EncodableUserToJSON,
    EncodableUserToJSONTyped,
} from './EncodableUser';

/**
 * 
 * @export
 * @interface GetUserResponse
 */
export interface GetUserResponse {
    /**
     * 
     * @type {EncodableUser}
     * @memberof GetUserResponse
     */
    user: EncodableUser;
}

/**
 * Check if a given object implements the GetUserResponse interface.
 */
export function instanceOfGetUserResponse(value: object): value is GetUserResponse {
    if (!('user' in value) || value['user'] === undefined) return false;
    return true;
}

export function GetUserResponseFromJSON(json: any): GetUserResponse {
    return GetUserResponseFromJSONTyped(json, false);
}

export function GetUserResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetUserResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'user': EncodableUserFromJSON(json['user']),
    };
}

export function GetUserResponseToJSON(json: any): GetUserResponse {
    return GetUserResponseToJSONTyped(json, false);
}

export function GetUserResponseToJSONTyped(value?: GetUserResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'user': EncodableUserToJSON(value['user']),
    };
}

