/* tslint:disable */
/* eslint-disable */
/**
 * journly-server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { EncodableUser } from './EncodableUser';
import {
    EncodableUserFromJSON,
    EncodableUserFromJSONTyped,
    EncodableUserToJSON,
    EncodableUserToJSONTyped,
} from './EncodableUser';

/**
 * 
 * @export
 * @interface GetUsersResponse
 */
export interface GetUsersResponse {
    /**
     * 
     * @type {Array<EncodableUser>}
     * @memberof GetUsersResponse
     */
    users: Array<EncodableUser>;
}

/**
 * Check if a given object implements the GetUsersResponse interface.
 */
export function instanceOfGetUsersResponse(value: object): value is GetUsersResponse {
    if (!('users' in value) || value['users'] === undefined) return false;
    return true;
}

export function GetUsersResponseFromJSON(json: any): GetUsersResponse {
    return GetUsersResponseFromJSONTyped(json, false);
}

export function GetUsersResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetUsersResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'users': ((json['users'] as Array<any>).map(EncodableUserFromJSON)),
    };
}

export function GetUsersResponseToJSON(json: any): GetUsersResponse {
    return GetUsersResponseToJSONTyped(json, false);
}

export function GetUsersResponseToJSONTyped(value?: GetUsersResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'users': ((value['users'] as Array<any>).map(EncodableUserToJSON)),
    };
}

