/* tslint:disable */
/* eslint-disable */
/**
 * journly-server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateInformation
 */
export interface UpdateInformation {
    /**
     * 
     * @type {string}
     * @memberof UpdateInformation
     */
    email?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateInformation
     */
    username?: string | null;
}

/**
 * Check if a given object implements the UpdateInformation interface.
 */
export function instanceOfUpdateInformation(value: object): value is UpdateInformation {
    return true;
}

export function UpdateInformationFromJSON(json: any): UpdateInformation {
    return UpdateInformationFromJSONTyped(json, false);
}

export function UpdateInformationFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateInformation {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'] == null ? undefined : json['email'],
        'username': json['username'] == null ? undefined : json['username'],
    };
}

export function UpdateInformationToJSON(json: any): UpdateInformation {
    return UpdateInformationToJSONTyped(json, false);
}

export function UpdateInformationToJSONTyped(value?: UpdateInformation | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'email': value['email'],
        'username': value['username'],
    };
}

