DROP TABLE IF EXISTS journals;
DROP TABLE IF EXISTS user_journals;

CREATE TABLE journals (
  id UUID PRIMARY KEY,
  owner_id UUID NOT NULL REFERENCES users,
  CONTENT TEXT NOT NULL,
  last_edit TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE user_journals (
  user_id UUID NOT NULL REFERENCES users,
  journal_id UUID NOT NULL REFERENCES journals ON DELETE CASCADE,
  PRIMARY KEY (user_id, journal_id)
);
